### ISSUE TITLE
Deprecation warnings for rspec 3

### ISSUE THREAD

**Issue by justin808** [rubiety/nilify_blanks#19]
Maybe the code could be structured to avoid these?

```
Deprecation Warnings:

`failure_message_for_should_not` is deprecated. Use `failure_message_when_negated` instead. Called from bundler/gems/nilify_blanks-36503fb06364/lib/nilify_blanks/matchers.rb:36:in `block in <top (required)>'.

`failure_message_for_should` is deprecated. Use `failure_message` instead. Called from 
bundler/gems/nilify_blanks-36503fb06364/lib/nilify_blanks/matchers.rb:32:in `block in <top (required)>'.
```

**Comment by rubiety** [comment]
Fixed by @todd in commit a9d7420.
